const additionalInfo = [
  {
    name: "ImmigLawyers",
    demographic: ["18-35", "36-65", "65+"],
    measurement: "Number of immigration lawyers",
    category: "Community, Family, Wellness",
    lowerIsBetter: false,
  },
  {
    name: "PlanhubInternet",
    measurement: "Cost of internet plan",
    category: "Cost of Living",
    lowerIsBetter: true,
    demographic: "all",
  },
  {
    name: "RatesdotcaInsuranceAuto",
    measurement: "Cost of car insurance",
    category: "Cost of Living",
    lowerIsBetter: true,
    demographic: ["13-18", "19-35", "36-65"],
  },
  {
    name: "MinWage",
    measurement: "Minimum wage",
    category: "Employment Services",
    lowerIsBetter: false,
    demographic: ["13-18", "19-35", "36-65"],
  },
  {
    name: "PlanhubPhoneBasicPlan",
    measurement: "Cost of basic phone plan",
    category: "Cost of Living",
    lowerIsBetter: true,
    demographic: "all",
  },
  {
    name: "StatscanTuition",
    measurement: "Cost of tuition",
    category: "Education and Language Services",
    lowerIsBetter: true,
    demographic: ["13-18", "19-35"],
  },
  {
    name: "RentOneBr",
    measurement: "Cost of 1 bedroom appartment",
    category: "Cost of Living",
    lowerIsBetter: true,
    demographic: {
      minNumberOfPeople: 1,
      maxNumberOfPeople: 2,
    },
  },
  {
    name: "RentTwoBr",
    measurement: "Cost of 2 bedroom appartment",
    category: "Cost of Living",
    lowerIsBetter: true,
    demographic: {
      minNumberOfPeople: 3,
      maxNumberOfPeople: 4,
    },
  },
  {
    name: "RentThreeBr",
    measurement: "Cost of 3 bedroom appartment",
    category: "Cost of Living",
    lowerIsBetter: true,
    demographic: {
      minNumberOfPeople: 5,
      maxNumberOfPeople: 5,
    },
  },
  {
    name: "RentFourBr",
    measurement: "Cost of 4 bedroom appartment",
    category: "Cost of Living",
    lowerIsBetter: true,
    demographic: {
      minNumberOfPeople: 6,
      maxNumberOfPeople: 100,
    },
  },
  {
    name: "BridgingPrograms",
    measurement: "Number of bridging programs for professionals",
    category: "Employment Services",
    lowerIsBetter: false,
    demographic: ["19-35", "36-65"],
  },
  {
    name: "SkilledTraining",
    measurement: "Number of skilled jobs training programs",
    category: "Education and Language Services",
    lowerIsBetter: false,
    demographic: ["19-35"],
  },
  {
    name: "PolytechCollege",
    measurement: "Number of polytechnic colleges",
    category: "Education and Language Services",
    lowerIsBetter: false,
    demographic: ["19-35"],
  },
  {
    name: "PrivateCollege",
    measurement: "Number of private colleges",
    category: "Education and Language Services",
    lowerIsBetter: false,
    demographic: ["19-35"],
  },
  {
    name: "PrivateUni",
    measurement: "Number of private universities",
    category: "Education and Language Services",
    lowerIsBetter: false,
    demographic: ["19-35"],
  },
  {
    name: "PublicCollege",
    measurement: "Number of public colleges",
    category: "Education and Language Services",
    lowerIsBetter: false,
    demographic: ["19-35"],
  },
  {
    name: "PublicUni",
    measurement: "Number of public universities",
    category: "Education and Language Services",
    lowerIsBetter: false,
    demographic: ["19-35"],
  },
  {
    name: "ParentingPrograms",
    measurement: "Number of parenting supports",
    category: "Community, Family, Wellness",
    lowerIsBetter: false,
    demographic: ["0-12"],
  },
  {
    name: "SeniorRecPrograms",
    measurement: "Number of community programs for seniors",
    category: "Community, Family, Wellness",
    lowerIsBetter: false,
    demographic: ["65+"],
  },
  {
    name: "TeenRecPrograms",
    measurement: "Number of community programs for children and youth",
    category: "Community, Family, Wellness",
    lowerIsBetter: false,
    demographic: ["0-12", "13-18"],
  },
  {
    name: "AdultRecPrograms",
    measurement: "Number of community programs for adults",
    category: "Community, Family, Wellness",
    lowerIsBetter: false,
    demographic: ["19-35", "36-65"],
  },
  {
    name: "FamilyShelter",
    measurement: "Number of shelters for women, family, and youth",
    category: "Clothing, Furniture, Food Bank Services",
    lowerIsBetter: false,
    demographic: {
      minNumberOfPeople: 3,
      maxNumberOfPeople: 100,
    },
  },
  {
    name: "FoodBanks",
    measurement: "Number of food banks",
    category: "Clothing, Furniture, Food Bank Services",
    lowerIsBetter: false,
    demographic: "all",
  },
  {
    name: "FurnitureBank",
    measurement: "Number of affordable furniture banks and stores",
    category: "Clothing, Furniture, Food Bank Services",
    lowerIsBetter: false,
    demographic: "all",
  },
  {
    name: "ClothingBanks",
    measurement: "Number of affordable clothing banks and stores",
    category: "Clothing, Furniture, Food Bank Services",
    lowerIsBetter: false,
    demographic: "all",
  },
  {
    name: "Daycare",
    measurement: "Cost of public daycare",
    category: "Cost of Living",
    lowerIsBetter: true,
    demographic: ["0-12"],
  },
  {
    name: "EmploymentServices",
    measurement: "Number of employment support services",
    category: "Employment Services",
    lowerIsBetter: false,
    demographic: ["19-35", "36-65"],
  },
  {
    name: "TaxServices",
    measurement: "Number of tax supports",
    category: "Personal Banking  and Financial Services",
    lowerIsBetter: false,
    demographic: ["19-35", "36-65"],
  },
  {
    name: "Startup",
    measurement: "Number of business startup supports",
    category: "Starting a Business",
    lowerIsBetter: false,
    demographic: ["19-35", "36-65"],
  },
  {
    name: "SnowDays",
    measurement: "Number of snowy days",
    category: "Weather",
    lowerIsBetter: true,
    demographic: ["65+"],
  },
  {
    name: "TempSummer",
    measurement: "Average summer temperature",
    category: "Weather",
    lowerIsBetter: false,
    demographic: ["65+"],
  },
  {
    name: "YouthEmploymentCentre",
    measurement: "Number of youth employment centres",
    category: "Employment Services",
    lowerIsBetter: false,
    demographic: ["13-18"],
  },
  {
    name: "Libraries",
    measurement: "Number of libraries",
    category: "Community, Family, Wellness",
    lowerIsBetter: false,
    demographic: "all",
  },
  {
    name: "Mosque",
    measurement: "Number of mosques",
    category: "Ethnic Foods, Places of Worship, and Cultural",
    lowerIsBetter: false,
    demographic: ["65+"],
  },
  {
    name: "AfghanDemo",
    measurement: "Number of Afghan community associations",
    category: "Ethnic Foods, Places of Worship, and Cultural",
    lowerIsBetter: false,
    demographic: ["65+"],
  },
  {
    name: "EthnicMarkets",
    measurement: "Number of grocery stores selling Halal food",
    category: "Ethnic Foods, Places of Worship, and Cultural",
    lowerIsBetter: false,
    demographic: "all",
  },
  {
    name: "AfghanRestuarant",
    measurement: "Number of restaurants serving Halal food",
    category: "Ethnic Foods, Places of Worship, and Cultural",
    lowerIsBetter: false,
    demographic: "all",
  },
  {
    name: "SeniorTransit",
    measurement: "Cost of a senior's pass for public transport",
    category: "Cost of Living",
    lowerIsBetter: true,
    demographic: ["65+"],
  },
  {
    name: "AdultTransit",
    measurement: "Cost of an adult pass for public transport",
    category: "Cost of Living",
    lowerIsBetter: true,
    demographic: ["19-35", "36-65"],
  },
  {
    name: "YouthTransit",
    measurement: "Cost of a youth pass for public transport",
    category: "Cost of Living",
    lowerIsBetter: true,
    demographic: ["0-12", "13-18"],
  },
  {
    name: "ComputerClasses",
    measurement: "Number of computer training courses",
    category: "Education and Language Services",
    lowerIsBetter: false,
    demographic: ["36-65"],
  },
  {
    name: "EslClasses",
    measurement: "Number of English learning courses",
    category: "Education and Language Services",
    lowerIsBetter: false,
    demographic: ["18-35", "36-65"],
  },
  {
    name: "SeniorLiteracyPrograms",
    measurement: "Number of literacy learning supports for seniors",
    category: "Education and Language Services",
    lowerIsBetter: false,
    demographic: ["65+"],
  },
  {
    name: "FinancialLit",
    measurement: "Number of financial literacy courses",
    category: "Personal Banking  and Financial Services",
    lowerIsBetter: false,
    demographic: ["18-35", "36-65", "65+"],
  },
];

export default additionalInfo;
